"""empty message

Revision ID: 1ee75a91c719
Revises: 
Create Date: 2025-05-30 13:39:21.081639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee75a91c719'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('house_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('GrLivArea', sa.Integer(), nullable=False),
    sa.Column('YearBuilt', sa.Integer(), nullable=False),
    sa.Column('GarageCars', sa.Integer(), nullable=False),
    sa.Column('TotalBsmtSF', sa.Integer(), nullable=False),
    sa.Column('FullBath', sa.Integer(), nullable=False),
    sa.Column('OverallQual', sa.Integer(), nullable=False),
    sa.Column('Neighborhood', sa.String(length=50), nullable=False),
    sa.Column('predicted_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('house_records')
    # ### end Alembic commands ###
