"""empty message

Revision ID: 89069173da2c
Revises: 1ee75a91c719
Create Date: 2025-05-31 12:20:22.441354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89069173da2c'
down_revision: Union[str, None] = '1ee75a91c719'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house_records', sa.Column('area', sa.Integer(), nullable=False))
    op.add_column('house_records', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('house_records', sa.Column('garage', sa.Integer(), nullable=False))
    op.add_column('house_records', sa.Column('total_basement', sa.Integer(), nullable=False))
    op.add_column('house_records', sa.Column('bath', sa.Integer(), nullable=False))
    op.add_column('house_records', sa.Column('overall_quality', sa.Integer(), nullable=False))
    op.add_column('house_records', sa.Column('neighborhood', sa.String(length=50), nullable=False))
    op.add_column('house_records', sa.Column('price', sa.Float(), nullable=True))
    op.drop_column('house_records', 'OverallQual')
    op.drop_column('house_records', 'GrLivArea')
    op.drop_column('house_records', 'FullBath')
    op.drop_column('house_records', 'Neighborhood')
    op.drop_column('house_records', 'YearBuilt')
    op.drop_column('house_records', 'predicted_price')
    op.drop_column('house_records', 'GarageCars')
    op.drop_column('house_records', 'TotalBsmtSF')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('house_records', sa.Column('TotalBsmtSF', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('house_records', sa.Column('GarageCars', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('house_records', sa.Column('predicted_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('house_records', sa.Column('YearBuilt', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('house_records', sa.Column('Neighborhood', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('house_records', sa.Column('FullBath', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('house_records', sa.Column('GrLivArea', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('house_records', sa.Column('OverallQual', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('house_records', 'price')
    op.drop_column('house_records', 'neighborhood')
    op.drop_column('house_records', 'overall_quality')
    op.drop_column('house_records', 'bath')
    op.drop_column('house_records', 'total_basement')
    op.drop_column('house_records', 'garage')
    op.drop_column('house_records', 'year')
    op.drop_column('house_records', 'area')
    # ### end Alembic commands ###
